CONNECT 'jdbc:derby://10.11.1.101:1527/product-db;create=true;user=APP;password=APP';

CREATE TABLE PRODUCT(
   ID 		INT NOT NULL,
   DESCRIPTION 	VARCHAR(32),
   PRICE 	INT,
   PRIMARY KEY( ID )
);

INSERT INTO PRODUCT(ID, DESCRIPTION, PRICE) 
VALUES(1, 'Prodotto 1', 10); 

INSERT INTO PRODUCT(ID, DESCRIPTION, PRICE) 
VALUES(2, 'Prodotto 2', 20); 

INSERT INTO PRODUCT(ID, DESCRIPTION, PRICE) 
VALUES(3, 'Prodotto 3', 30); 

INSERT INTO PRODUCT(ID, DESCRIPTION, PRICE) 
VALUES(4, 'Prodotto 4', 40); 

INSERT INTO PRODUCT(ID, DESCRIPTION, PRICE) 
VALUES(5, 'Prodotto 5', 50); 

INSERT INTO PRODUCT(ID, DESCRIPTION, PRICE) 
VALUES(6, 'Prodotto 6', 60); 

INSERT INTO PRODUCT(ID, DESCRIPTION, PRICE) 
VALUES(7, 'Prodotto 7', 70); 

INSERT INTO PRODUCT(ID, DESCRIPTION, PRICE) 
VALUES(8, 'Prodotto 8', 80); 

INSERT INTO PRODUCT(ID, DESCRIPTION, PRICE) 
VALUES(9, 'Prodotto 9', 90); 

INSERT INTO PRODUCT(ID, DESCRIPTION, PRICE) 
VALUES(10, 'Prodotto 10', 100); 
