# 
# Vagrantfile per un singolo nodo (docker), su cui è installato Docker, 
# nonché Java e Gradle. 
# Basata su Ubuntu Trusty (14.04 LTS), mi sembra che Docker NON giri su Ubuntu Precise (12.04 LTS). 
# 

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Configurazioni comuni.

    # Ubuntu Trusty 64 VirtualBox.
    config.vm.box = "ubuntu/trusty64"
    # config.vm.box_url = "http://files.vagrantup.com/ubuntu/trusty64.box"

    # folder per i progetti Asw (/home/vagrant/projects)
    config.vm.synced_folder "../../projects/", "/home/vagrant/projects", :mount_options => ["dmode=777", "fmode=777"]

    # folder per le risorse condivise per gli ambienti Asw (/home/vagrant/shared/resources e /home/vagrant/shared/scripts) 
    config.vm.synced_folder "../shared/", "/home/vagrant/shared", :mount_options => ["dmode=777", "fmode=777"]

    # folder per i progetti docker Asw (per es., /home/vagrant/docker)
    config.vm.synced_folder "../../docker/", "/home/vagrant/docker", :mount_options => ["dmode=777", "fmode=777"]

    #
    # Configurazione del nodo "docker", che prevede: 
    # - Java 
    # - Docker 
    #
    config.vm.define "docker" do |node|
        node.vm.hostname = "docker"    
        node.vm.network "private_network", ip: "10.11.1.101", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
            v.memory = 2048 
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2211, id: 'ssh', auto_correct: true
        node.ssh.forward_agent = true
        # node.ssh.forward_x11 = true
 
        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        # node.vm.provision :shell, :inline => 'apt-get install unzip'

        node.vm.provision :shell, path: "../shared/scripts/setup-java.sh"
        node.vm.provision :shell, path: "../shared/scripts/setup-gradle.sh"
        node.vm.provision :shell, path: "../shared/scripts/setup-docker.sh"
        
        # aggiunge vagrant al gruppo di docker (richiede un reboot?) 
        node.vm.provision :shell, :inline => 'usermod -aG docker vagrant'
        
        # installa anche docker-compose 
        node.vm.provision :shell, path: "../shared/scripts/setup-docker-compose.sh"
  
        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo docker quasi completa'"
        node.vm.provision :shell, 
            inline: "echo  'riavviare il nodo con il comando vagrant reload'"

    end

end
