# 
# Vagrantfile per un singolo nodo (dev, developer) 
# per la compilazione dei progetti, 
# con Oracle Java e Gradle. 
# 

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Configurazioni comuni.

    # Ubuntu trusty 64 VirtualBox.
    config.vm.box = "ubuntu/trusty64"
    # config.vm.box_url = "http://files.vagrantup.com/ubuntu/trusty64.box"

    # folder per i progetti Asw (/home/vagrant/projects)
    config.vm.synced_folder "../../projects/", "/home/vagrant/projects", :mount_options => ["dmode=777", "fmode=777"]

    # folder per le risorse condivise per gli ambienti Asw (/home/vagrant/shared/resources e /home/vagrant/shared/scripts) 
    config.vm.synced_folder "../shared/", "/home/vagrant/shared", :mount_options => ["dmode=777", "fmode=777"]

    # folder per i progetti docker Asw (/home/vagrant/docker)
    # config.vm.synced_folder "../../docker/", "/home/vagrant/docker", :mount_options => ["dmode=777", "fmode=777"]

    #
    # Configurazione del nodo "dev", che prevede: 
    # - Oracle Java SDK 8 
    # - Gradle 
    #
    config.vm.define "dev" do |node|
        node.vm.hostname = "dev"    
        node.vm.network "private_network", ip: "10.11.1.151", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
            v.memory = 1024 
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2229, id: 'ssh', auto_correct: true 
        node.ssh.forward_agent = true
 
        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        node.vm.provision :shell, path: "../shared/scripts/setup-java.sh"
        node.vm.provision :shell, path: "../shared/scripts/setup-gradle.sh"
  
        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo developer completata'"

    end

end
